version: 2.1

jobs:
  validate:
    docker:
      - auth:
          password: $DOCKER_PASSWORD
          username: $DOCKER_USERNAME
      - image: trussworks/circleci:efb1042e31538677779971798e0912390f699e72
    steps:
      - checkout
      - restore_cache:
          keys:
            - pre-commit-dot-cache-{{ checksum ".pre-commit-config.yaml" }}
            - go-mod-sources-v1-{{ checksum "go.sum" }}-{{ checksum "scripts/check-go-version" }}
      - run:
          name: Adding go binaries to $PATH
          command: |
            echo 'export PATH=${PATH}:~/go/bin' >> $BASH_ENV
            source $BASH_ENV
      - run: go get github.com/jstemmer/go-junit-report
      - run:
          name: Run pre-commit
          command: pre-commit run --all-files
      - save_cache:
          key: pre-commit-dot-cache-{{ checksum ".pre-commit-config.yaml" }}
          paths:
            - ~/.cache/pre-commit
      - save_cache:
          key: go-mod-sources-v1-{{ checksum "go.sum" }}-{{ checksum "scripts/check-go-version" }}
          paths:
            - "~/go/pkg/mod"

workflows:
  version: 2.1
  validate:
    jobs:
      - validate
