version: 2.1

jobs:
  validate:
    docker:
      - auth:
          password: $DOCKER_PASSWORD
          username: $DOCKER_USERNAME
      - image: trussworks/circleci:efb1042e31538677779971798e0912390f699e72

    steps:
    - checkout
    - restore_cache:
        keys:
        - pre-commit-dot-cache-{{ checksum ".pre-commit-config.yaml" }}
        - go-mod-sources-v1-{{ checksum "go.sum" }}-{{ checksum "scripts/check-go-version"
          }}
    - run:
        command: 'echo ''export PATH=${PATH}:~/go/bin'' >> $BASH_ENV

          source $BASH_ENV

          '
        name: Adding go binaries to $PATH
    - run: go get github.com/jstemmer/go-junit-report
    - run:
        command: pre-commit run --all-files
        name: Run pre-commit
    - save_cache:
        key: pre-commit-dot-cache-{{ checksum ".pre-commit-config.yaml" }}
        paths:
        - ~/.cache/pre-commit
    - save_cache:
        key: go-mod-sources-v1-{{ checksum "go.sum" }}-{{ checksum "scripts/check-go-version"
          }}
        paths:
        - ~/go/pkg/mod
references:
  circleci: trussworks/circleci:6986bb9022e5a83599feb66a7128a2d0fa12732a
version: 2.1
workflows:
  validate:
    jobs:
    - validate:
        context:
        - org-global
  version: 2.1
